services:
  - type: web
    name: saborxpress-backend-2-0
    env: docker
    plan: free
    region: ohio
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_SSLMODE
        value: require
      - key: APP_KEY
        sync: false # Debes ponerla manualmente en el panel de Render por seguridad
      - key: DB_HOST
        sync: false # Los datos de Supabase van en el panel
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
